DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS todo_list;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email_address TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE todo_list (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  author_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  item_text TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);